playbook_name: "gitea_service_backup"
registries:
  - "./registry/directory_actions.py"
  - "./registry/restic_actions.py"
  - "./registry/dbpg_actions.py"
  - "./registry/docker_actions.py"
log_dir: "./"

global_context:
  repoPath: "/home/esilva/Trash/test_borgmatic/destiny2"
  passwordFile: "/home/esilva/Trash/test_borgmatic/pass_file"

acts:
  - name: "DB Dump and Backup"
    steps:
      - name: "find database container"
        action: "get_service_container_name"
        context:
          service_name: "gitea-db"
    
      - name: "dump database"
        action: "dump_container_pg_db"
        context:
          dump_path: "/tmp/db_dump.sql"
          db_user: "gitea"
          database: "gitea"
    
      - name: "restic database backup"
        action: "backup_data_to_restic_repo"
        context:
          source_path: "/tmp/db_dump.sql"
          tags: ["gitea", "db-dump"]

  - name: "Backup gitea data"
    steps:
      - name: "backup gitea mount points data"
        action: "backup_data_to_restic_repo"
        context:
          source_path: "/home/esilva/Trash/docker-compose/resources/gitea/gitea_data/"
          tags: ["gitea", "data"]

  - name: "Backup gitea PG data"
    steps:
      - name: "backup gitea database mount points data"
        action: "backup_data_to_restic_repo"
        context:
          source_path: "/home/esilva/Trash/docker-compose/resources/gitea/postgres_data/"
          tags: ["gitea", "db-data"]
