playbook_name: "test_playbook"
registries:
  - "./registry/directory_actions.py"
  - "./registry/restic_actions.py"
  - "./registry/dbpg_actions.py"
  - "./registry/docker_actions.py"
log_dir: "./"

global_context:
  repoPath: "/home/esilva/Trash/test_borgmatic/destiny2"
  passwordFile: "/home/esilva/Trash/test_borgmatic/pass_file"

steps:
  - name: "dump rusty-packages db"
    actions:
      dump_database: "dump_pg_database"
    context:
      serviceName: "gitea-db"
      tmpPathPrefix: "/tmp/db_dump.sql"
  - name: "backup db to restic repo"
    actions:
      dump_database: "backup_data_to_restic_repo"
    context:
      sourcePath: "/tmp/db_dump.sql"
      serviceTag: "gitea-db"
  # - name: "backup rusty-packages"
  #   actions:
  #     create_repo_dir_if_not_exists: "create_dir_if_not_exists"
  #     create_repo_if_not_exists: "create_repo_if_not_exists"
  #     check_restic_environment: "check_restic_environment"
  #     backup_data_to_restic_repo: "backup_data_to_restic_repo"
  #   context:
  #     sourcePath: "/home/esilva/Trash/rusty_packages"
  #     serviceTag: "rusty-packages"
